### ISSUE TITLE
SamsungTV (Tizen) - No token is provided

### ISSUE THREAD

**Issue by Grothesk242** [iobroker-community-adapters/ioBroker.samsung#113]
When starting the adapter, the TV is powered on and the 'Authorization required' pop-up show on the screen. 
Clicking 'OK', the pop up disappears. Below error is being shown and no objects are created. 

```
2022-05-26 23:04:51.145  - info: samsung.0 (123101) starting. Version 0.5.8 in /opt/iobroker/node_modules/iobroker.samsung, node: v16.15.0, js-controller: 4.0.23
2022-05-26 23:04:50.257  - debug: samsung.0 (123101) Redis Objects: Use Redis connection: 0.0.0.0:9001
2022-05-26 23:04:50.306  - debug: samsung.0 (123101) Objects client ready ... initialize now
2022-05-26 23:04:50.311  - debug: samsung.0 (123101) Objects create System PubSub Client
2022-05-26 23:04:50.313  - debug: samsung.0 (123101) Objects create User PubSub Client
2022-05-26 23:04:50.399  - debug: samsung.0 (123101) Objects client initialize lua scripts
2022-05-26 23:04:50.410  - debug: samsung.0 (123101) Objects connected to redis: 0.0.0.0:9001
2022-05-26 23:04:50.444  - debug: samsung.0 (123101) Redis States: Use Redis connection: 0.0.0.0:9000
2022-05-26 23:04:50.476  - debug: samsung.0 (123101) States create System PubSub Client
2022-05-26 23:04:50.482  - debug: samsung.0 (123101) States create User PubSub Client
2022-05-26 23:04:50.544  - debug: samsung.0 (123101) States connected to redis: 0.0.0.0:9000
2022-05-26 23:04:50.666  - debug: samsung.0 (123101) Plugin sentry Initialize Plugin (enabled=true)
2022-05-26 23:04:51.145  - info: samsung.0 (123101) starting. Version 0.5.8 in /opt/iobroker/node_modules/iobroker.samsung, node: v16.15.0, js-controller: 4.0.23
2022-05-26 23:04:56.483  - error: samsung.0 (123101) Connection to TV failed. Is the IP correct? Is the TV switched on? TypeError: Cannot read properties of undefined (reading 'ws')
```

**Comment by Apollon77** [comment]
Please update adappter fom Github, then we should see some more error log ... 

BTW: GitHub installs with npm 6 can take 10+minutes ... just wait

**Comment by Grothesk242** [comment]
```
2022-05-27 19:19:37.196  - info: samsung.0 (152281) starting. Version 0.5.8 (non-npm: iobroker-community-adapters/ioBroker.samsung#2a3f746e6ab8f9dd99a5fb510411d0cf33c53a26) in /opt/iobroker/node_modules/iobroker.samsung, node: v18.2.0, js-controller: 4.0.23
2022-05-27 19:19:42.692  - error: samsung.0 (152281) Connection to TV failed. Is the IP correct? Is the TV switched on? TypeError: Cannot read properties of undefined (reading 'ws')
2022-05-27 19:19:42.703  - error: samsung.0 (152281) TypeError: Cannot read properties of undefined (reading 'ws')
    at /opt/iobroker/node_modules/iobroker.samsung/lib/samsungtv/build/device.js:135:42
    at new Promise (<anonymous>)
    at new F (/opt/iobroker/node_modules/core-js/library/modules/_export.js:36:28)
    at SamsungSmartTV._callee$ (/opt/iobroker/node_modules/iobroker.samsung/lib/samsungtv/build/device.js:134:66)
    at tryCatch (/opt/iobroker/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/opt/iobroker/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/opt/iobroker/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/opt/iobroker/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /opt/iobroker/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

**Comment by Apollon77** [comment]
Cool ... please try GitHub update again ...

**Comment by Grothesk242** [comment]
Cool! Works now! 

```
2022-05-27 20:43:42.937  - info: samsung.0 (156199) starting. Version 0.5.8 (non-npm: iobroker-community-adapters/ioBroker.samsung#593d73ae6eff5330cbd5292867a904a2880b933c) in /opt/iobroker/node_modules/iobroker.samsung, node: v18.2.0, js-controller: 4.0.23
2022-05-27 20:43:54.966  - info: samsung.0 (156199) -----------------------------------------
2022-05-27 20:43:54.969  - info: samsung.0 (156199) Confirm on your TV to get a Token
2022-05-27 20:43:54.970  - info: samsung.0 (156199) -----------------------------------------
2022-05-27 20:43:54.971  - info: samsung.0 (156199) Token: 15407140
2022-05-27 20:43:54.972  - info: samsung.0 (156199) -----------------------------------------
2022-05-27 20:43:55.122  - warn: samsung.0 (156199) State "samsung.0.Power.checkOnOff" has no existing object, this might lead to an error in future versions
2022-05-27 20:44:16.061  - info: host.chet stopInstance system.adapter.samsung.0 (force=false, process=true)
2022-05-27 20:44:16.077  - info: samsung.0 (156199) Got terminate signal TERMINATE_YOURSELF
2022-05-27 20:44:16.084  - info: host.chet stopInstance system.adapter.samsung.0 send kill signal
2022-05-27 20:44:16.082  - info: samsung.0 (156199) terminating
2022-05-27 20:44:16.085  - info: samsung.0 (156199) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2022-05-27 20:44:16.694  - info: host.chet instance system.adapter.samsung.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2022-05-27 20:44:19.192  - info: host.chet instance system.adapter.samsung.0 started with pid 156228
2022-05-27 20:44:21.913  - info: samsung.0 (156228) starting. Version 0.5.8 (non-npm: iobroker-community-adapters/ioBroker.samsung#593d73ae6eff5330cbd5292867a904a2880b933c) in /opt/iobroker/node_modules/iobroker.samsung, node: v18.2.0, js-controller: 4.0.23
2022-05-27 20:44:28.833  - info: samsung.0 (156228) -----------------------------------------
2022-05-27 20:44:28.834  - info: samsung.0 (156228) Confirm on your TV to get a Token
2022-05-27 20:44:28.835  - info: samsung.0 (156228) -----------------------------------------
2022-05-27 20:44:28.836  - info: samsung.0 (156228) Token: 15407140
2022-05-27 20:44:28.837  - info: samsung.0 (156228) -----------------------------------------
```

**Comment by Apollon77** [comment]
Cool, Official updates goes out
