### ISSUE TITLE
KEY_ENTER and KEY_RETURN -> error: Key code not availlable

### ISSUE THREAD

**Issue by BramTown** [iobroker-community-adapters/ioBroker.samsung#121]
Adapter v0.5.11
ioBroker v6.2.4
node v16.16.0
npm v8.11.0

When I try to use the "KEY_ENTER" or KEY_RETURN Command, it ends in an error.

`
host.ioBroker |   | 2022-07-23 23:57:06.662 | error | instance system.adapter.samsung.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | -- | --
host.ioBroker |   | 2022-07-23 23:57:06.661 | error | Caught by controller[2]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
host.ioBroker |   | 2022-07-23 23:57:06.661 | error | Caught by controller[2]: at Object.send (/opt/iobroker/node_modules/iobroker.samsung/main.js:333:29)
host.ioBroker |   | 2022-07-23 23:57:06.661 | error | Caught by controller[2]: at SamsungSmartTV.sendKey (/opt/iobroker/node_modules/iobroker.samsung/lib/samsungtv/build/device.js:284:30)
host.ioBroker |   | 2022-07-23 23:57:06.661 | error | Caught by controller[2]: at SamsungSmartTV.<anonymous> (/opt/iobroker/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
host.ioBroker |   | 2022-07-23 23:57:06.660 | error | Caught by controller[2]: at new F (/opt/iobroker/node_modules/core-js/library/modules/_export.js:36:28)
host.ioBroker |   | 2022-07-23 23:57:06.660 | error | Caught by controller[2]: at new Promise (<anonymous>)
host.ioBroker |   | 2022-07-23 23:57:06.660 | error | Caught by controller[2]: at /opt/iobroker/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
host.ioBroker |   | 2022-07-23 23:57:06.659 | error | Caught by controller[2]: at step (/opt/iobroker/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
host.ioBroker |   | 2022-07-23 23:57:06.659 | error | Caught by controller[2]: at Generator.prototype.<computed> [as next] (/opt/iobroker/node_modules/regenerator-runtime/runtime.js:114:21)
host.ioBroker |   | 2022-07-23 23:57:06.659 | error | Caught by controller[2]: at Generator.invoke [as _invoke] (/opt/iobroker/node_modules/regenerator-runtime/runtime.js:296:22)
host.ioBroker |   | 2022-07-23 23:57:06.659 | error | Caught by controller[2]: at tryCatch (/opt/iobroker/node_modules/regenerator-runtime/runtime.js:62:40)
host.ioBroker |   | 2022-07-23 23:57:06.658 | error | Caught by controller[2]: at SamsungSmartTV._callee2$ (/opt/iobroker/node_modules/iobroker.samsung/lib/samsungtv/build/device.js:246:39)
host.ioBroker |   | 2022-07-23 23:57:06.658 | error | Caught by controller[2]: Error: Key code not available
host.ioBroker |   | 2022-07-23 23:57:06.657 | error | Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
samsung.0 | 629959 | 2022-07-23 23:57:06.088 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
`

**Comment by BramTown** [comment]
correction:
the KEY_RETURN is working, it seems that it was blocked after using KEY_ENTER
